#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Variables
//Speed defined as 50u
int speed = 50;
int rot = 360; //GPLv3//
int x = 50;

//Functions
//Int X defined as threshold
void lightMove(){

	if(SensorValue(lightSensor) > x){
	motor[motorC] = speed;
	motor[motorB] = 0;
	}
	else{
	motor[motorC] = 0;
	motor[motorB] = speed;
	}

}

task main()
{
	nMotorEncoder[motorC] = 0;
	nMotorEncoder[motorB] = 0;

	//Do this when not touched
	while (nMotorEncoder[motorB] < rot*3) {
		motor[motorB] = speed;
	}
	motor[motorB] = 0;
}
