#pragma config(Sensor, S3,     LightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Speed defined as 25u
int speed = 25;
int x = 50
//Int X defined as threshold
void lightMove(){

	if(SensorValue(LightSensor) > x){
	motor[motorC] = speed;
	motor[motorB] = 0;
	}
	else{
	motor[motorC] = 0;
	motor[motorB] = speed;
	}

}

task main()
{
	//Always do this
 while (true) {
 	lightMove();
 }

}
